### ISSUE TITLE
HtmlToExcelFactory可否加个直接读取html字符串做为参数的方法，这样会方便很多

### ISSUE THREAD

**Issue by beebon** [liaochong/html2excel#26]
**Additional context**
如题，建议加个方法以html字符串做为参数

**Comment by liaochong** [comment]
谢谢你的提议，在1月1日发布的1.3.0版本加入，该版本会对性能、内存占用以及默认Excel构建器提供更方便、强大的支持，还请多多关注！如有问题请随时联系～谢谢
